[build-system]
requires = ["cython", "setuptools >= 61.0.0", "wheel"]

[project]
name = 'liftover'
version = '1.4.1'
description = 'Package for converting between genome build coordinates'
readme = 'README.md'
requires-python = '>=3.9'
authors = [
    {name = "Jeremy McRae", email = 'jmcrae@illumina.com'},
]

dependencies = [
    'urllib3',
]

classifiers = [
    "License :: OSI Approved :: MIT License",
    'Development Status :: 4 - Beta',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
]

[tool.setuptools]
packages = [
    'liftover',
]

[tool.setuptools.package-data]
liftover = ['py.typed', '*.pyi']

[project.urls]
homepage = 'https://github.com/jeremymcrae/liftover'
