name: liftover

on: 
  push:
  pull_request:
  schedule:
    - cron: "33 3 3 * *"

jobs:
  default_tests:
    name: test package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04-arm', 'ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install setuptools build
          pip install .
          python -m unittest discover

  build_wheels:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-24.04-arm', 'ubuntu-latest', 'macos-latest', 'windows-latest']
        python: ["cp38", "cp39", "cp310", "cp311", "cp312", "cp313", "cp314"]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        env:
          CIBW_BUILD: ${{ matrix.python }}-*
          CIBW_TEST_COMMAND: "python -m unittest discover -s {project}"
          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64:latest

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: artifact-${{ matrix.os }}-${{ matrix.python }}

  build_sdist:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.12'

      - name: Build sdist
        run: |
          python -m pip install --upgrade pip
          pip install setuptools build
          python -m build --sdist
          pip install .
          python -m unittest discover

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
          name: artifact-source

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    # upload to PyPI on every tag starting with 'v'
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    # alternatively, to publish when a GitHub Release is created, use the following rule:
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          merge-multiple: true
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
          # To test: repository_url: https://test.pypi.org/legacy/
